services:
  app:
    build: ../
    container_name: user-manager-app
    ports:
      - "8080:8080"
    env_file:
      - app.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: postgres:13.16
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - db.env

volumes:
  postgres_data: